In [2]:
import numpy as np
n=4
m=5
z=5

In [3]:
def Numeric(a,d,cnum):
    max=np.amax(a,axis=0)[cnum]
    min=np.amin(a,axis=0)[cnum]
    denominator=max-min
    for i in range(n):
        for j in range(n):
            if i==j:
                d[cnum][i][j]=0
            d[cnum][i][j]=abs(a[i][cnum]-a[j][cnum])/denominator
    return d
    

In [4]:
def Ordinal(a,d,cnum):
    temp=[]
    for i in range(n):
        temp.append((a[i][cnum]-1)/(z-1))
    #print(a)
    for i in range(n):
        for j in range(n):
            if i==j:
                d[cnum][i][j]=0
            
            else:
                d[cnum][i][j]=np.linalg.norm(temp[i]-temp[j])
    return d
    

In [5]:
def NominalORBinary(a,d,cnum):
 
    for i in range(n):
        for j in range(n):
            if i==j:
                d[cnum][i][j]=0
            if a[i][cnum]==a[j][cnum]:
                d[cnum][i][j]=0
            else:
                d[cnum][i][j]=1
    return d

In [6]:
def DissimilarityMatrix(d,D):
    temp=0
    for i in range(n):
        
        for j in range(n):
            if i==j:
                D[i][j]=0
            for k in range(m):
                temp+=(d[k][i][j])
            D[i][j]=temp/m
            temp=0
    return D

In [7]:
a=np.zeros((n,m))
d=np.zeros((m,n,n))
D=np.zeros((n,n))

In [8]:
dict={"Y":1,"N":0}

In [9]:
for i in range(n):
    print("Enter the details of Family "+chr(ord('A')+i));
    
    for j in range(m):
       entry=input()
       if entry in dict.keys():
            entry=dict[entry]
       a[i][j]=entry
       
print(a)


Enter the details of Family A
30
1
1
5
Y
Enter the details of Family B
60
1
5
2
N
Enter the details of Family C
30
3
3
4
Y
Enter the details of Family D
45
1
1
2
Y
[[30.  1.  1.  5.  1.]
 [60.  1.  5.  2.  0.]
 [30.  3.  3.  4.  1.]
 [45.  1.  1.  2.  1.]]


In [10]:
attribute_type=[]
for i in range(m):
    attribute_type.append(input("Enter Attribute "+str(i+1)+" Type:"))

Enter Attribute 1 Type:Numeric
Enter Attribute 2 Type:Nominal
Enter Attribute 3 Type:Nominal
Enter Attribute 4 Type:Ordinal
Enter Attribute 5 Type:Binary


In [11]:
for i in range(m):
    if attribute_type[i]=='Numeric':
        d=Numeric(a,d,i)
    elif attribute_type[i]=='Nominal':
        d=NominalORBinary(a,d,i)
    elif attribute_type[i]=='Binary':
        d=NominalORBinary(a,d,i)
    elif attribute_type[i]=='Ordinal':
        d=Ordinal(a,d,i)

In [12]:
print("Individual Dissimilirity Matrices are:")
print(d)

Individual Dissimilirity Matrices are:
[[[0.   1.   0.   0.5 ]
  [1.   0.   1.   0.5 ]
  [0.   1.   0.   0.5 ]
  [0.5  0.5  0.5  0.  ]]

 [[0.   0.   1.   0.  ]
  [0.   0.   1.   0.  ]
  [1.   1.   0.   1.  ]
  [0.   0.   1.   0.  ]]

 [[0.   1.   1.   0.  ]
  [1.   0.   1.   1.  ]
  [1.   1.   0.   1.  ]
  [0.   1.   1.   0.  ]]

 [[0.   0.75 0.25 0.75]
  [0.75 0.   0.5  0.  ]
  [0.25 0.5  0.   0.5 ]
  [0.75 0.   0.5  0.  ]]

 [[0.   1.   0.   0.  ]
  [1.   0.   1.   1.  ]
  [0.   1.   0.   0.  ]
  [0.   1.   0.   0.  ]]]


In [13]:
D=DissimilarityMatrix(d,D)
print("Mixed Attribute Dissimilirity Matrix:")
print(D)

Mixed Attribute Dissimilirity Matrix:
[[0.   0.75 0.45 0.25]
 [0.75 0.   0.9  0.5 ]
 [0.45 0.9  0.   0.6 ]
 [0.25 0.5  0.6  0.  ]]
